import { test, expect, Page } from '@playwright/test';
import path from 'path';

// Coverage for issue #18 — closes the longstanding gap flagged in
// HANDOFF.md since #10: zero Playwright coverage of the selection UI
// (#6-#9: drag-select a region on upload, resize handles, pan, zoom,
// confirm/clear). Also adds a touch-emulated test that pins down the
// mobile drag-select bug reported by the user and confirmed at the code
// level (js/app.js's selectCanvas only wires up mousedown/mousemove/mouseup
// — grepping the whole file for "touch"/"Touch"/"pointer"/"Pointer" turns
// up zero event-handling code; the only matches are an unrelated local
// variable name in the mask-trim algorithm and the "Apple Touch" icon
// label string) — see the "touch input" describe block at the bottom.
//
// tests/fixtures/test-logo.png (32x32) is too small to trigger the
// selection view at all — SELECT_SKIP_MAX_DIM (js/app.js) is 256px, and an
// image at or below that in both dimensions skips straight to the
// immediate-trace-ready flow. tests/fixtures/select-sheet.png (new, 512x512)
// was generated for this issue: a white sheet with two distinct black
// icons — a filled square near the top-left (source px 40,40 to 200,200)
// and a filled circle near the bottom-right (centered 380,380, radius 90) —
// modeling the multi-icon-sheet scenario the selection UI targets, with
// real, non-trivial subject content for auto-trim and pan assertions to
// grab onto. Generated by a pure-Node PNG encoder (no canvas/native image
// lib is present in this repo's node_modules) — see git history for the
// generation script if it needs regenerating.

const SHEET_FIXTURE = path.resolve(__dirname, 'fixtures/select-sheet.png');
// Same two-icon layout as SHEET_FIXTURE but with genuinely anti-aliased
// (soft) icon edges instead of perfectly sharp/binary ones — see the
// generation-script comment in the fixture's own history and the "known
// bugs found in this session" describe block below for why SHEET_FIXTURE's
// hard edges specifically cannot be used for the auto-trim regression
// test below.
const AA_SHEET_FIXTURE = path.resolve(__dirname, 'fixtures/select-sheet-aa.png');
const SMALL_FIXTURE = path.resolve(__dirname, 'fixtures/test-logo.png');

async function uploadSheet(page: Page, fixture = SHEET_FIXTURE) {
  await page.goto('http://localhost:4321');
  await page.locator('#file-input').setInputFiles(fixture);
  await expect(page.locator('#select-wrap')).toBeVisible({ timeout: 3000 });
}

async function canvasBox(page: Page) {
  const box = await page.locator('#select-canvas').boundingBox();
  if (!box) throw new Error('select-canvas has no bounding box');
  return box;
}

// Drags a plain left-button mouse drag between two points expressed as
// canvas-local (backing-pixel) offsets. The canvas is drawn at
// selectBaseScale = min(1, 260/imgWidth) with no further CSS scaling
// (#select-canvas has max-width:100%/height:auto but the fixtures used
// here are well under any container width, so intrinsic size == CSS
// display size), so canvas-local offsets map ~1:1 to viewport px added to
// the canvas's boundingBox origin.
async function dragOnCanvas(page: Page, x1: number, y1: number, x2: number, y2: number) {
  const cb = await canvasBox(page);
  await page.mouse.move(cb.x + x1, cb.y + y1);
  await page.mouse.down();
  await page.mouse.move(cb.x + (x1 + x2) / 2, cb.y + (y1 + y2) / 2);
  await page.mouse.move(cb.x + x2, cb.y + y2);
  await page.mouse.up();
}

async function samplePixel(page: Page, x: number, y: number): Promise<[number, number, number]> {
  return page.evaluate(({ x, y }) => {
    const el = document.getElementById('select-canvas') as HTMLCanvasElement;
    const ctx = el.getContext('2d')!;
    const d = ctx.getImageData(Math.round(x), Math.round(y), 1, 1).data;
    return [d[0], d[1], d[2]] as [number, number, number];
  }, { x, y });
}

test.describe('selection UI — threshold gating', () => {
  test('images above the 256px threshold open the selection view instead of tracing immediately', async ({ page }) => {
    await uploadSheet(page);
    await expect(page.locator('#select-wrap')).toBeVisible();
    await expect(page.locator('#dropzone')).toBeHidden();
    await expect(page.locator('#thumb-wrap')).toBeHidden();
    await expect(page.locator('#select-confirm-btn')).toBeDisabled();
    const cb = await canvasBox(page);
    expect(cb.width).toBeGreaterThan(0);
    expect(cb.height).toBeGreaterThan(0);
  });

  test('images at or below the 256px threshold skip the selection view entirely', async ({ page }) => {
    await page.goto('http://localhost:4321');
    await page.locator('#file-input').setInputFiles(SMALL_FIXTURE);
    await expect(page.locator('#trace-btn')).toBeEnabled({ timeout: 3000 });
    await expect(page.locator('#select-wrap')).toBeHidden();
    await expect(page.locator('#thumb-wrap')).toBeVisible();
  });
});

test.describe('selection UI — desktop (mouse)', () => {
  test.beforeEach(async ({ page }) => {
    await uploadSheet(page);
  });

  test('dragging draws a new selection box and enables "Use selection"', async ({ page }) => {
    await expect(page.locator('#select-rect')).toBeHidden();
    await dragOnCanvas(page, 20, 20, 100, 100);
    await expect(page.locator('#select-rect')).toBeVisible();
    await expect(page.locator('#select-confirm-btn')).toBeEnabled();

    const rect = await page.locator('#select-rect').boundingBox();
    expect(rect).not.toBeNull();
    expect(rect!.width).toBeGreaterThan(50);
    expect(rect!.height).toBeGreaterThan(50);
  });

  test('a drag smaller than the minimum select size does not produce a usable selection', async ({ page }) => {
    // MIN_SELECT_PX = 6 (js/app.js) — a 3x3 drag is below that floor, so
    // onSelectDragEnd's 'new' branch should discard it (selectionBox reset
    // to null) rather than leave a degenerate sliver selected.
    await dragOnCanvas(page, 50, 50, 53, 53);
    await expect(page.locator('#select-rect')).toBeHidden();
    await expect(page.locator('#select-confirm-btn')).toBeDisabled();
  });

  test('resizing via a corner handle grows the selection box', async ({ page }) => {
    await dragOnCanvas(page, 20, 20, 100, 100);
    const before = await page.locator('#select-rect').boundingBox();
    expect(before).not.toBeNull();

    // Grab the se handle (bottom-right corner of the box, within
    // hitTestHandle's HANDLE_TOL=8px tolerance) and drag it outward.
    const cb = await canvasBox(page);
    await page.mouse.move(before!.x + before!.width, before!.y + before!.height);
    await page.mouse.down();
    await page.mouse.move(cb.x + 200, cb.y + 200, { steps: 5 });
    await page.mouse.up();

    const after = await page.locator('#select-rect').boundingBox();
    expect(after).not.toBeNull();
    expect(after!.width).toBeGreaterThan(before!.width);
    expect(after!.height).toBeGreaterThan(before!.height);
    // The opposite (nw) corner should stay anchored in place — a resize
    // grows from the dragged corner, not from the box center.
    expect(Math.abs(after!.x - before!.x)).toBeLessThan(3);
    expect(Math.abs(after!.y - before!.y)).toBeLessThan(3);
  });

  test('panning inside the box moves the underlying image content while the frame stays fixed', async ({ page }) => {
    // Box drawn over the square icon (source 40,40-200,200 -> display
    // ~20,20-102,102 at this fixture's ~0.508 selectBaseScale).
    await dragOnCanvas(page, 20, 20, 100, 100);
    const rectBefore = await page.locator('#select-rect').boundingBox();

    const before = await samplePixel(page, 60, 60); // deep inside the icon — should read near-black
    expect(before[0]).toBeLessThan(60);

    // Drag from inside the box (not on a handle) far outside the canvas —
    // the drag continues via document-level listeners (js/app.js
    // onSelectDrag/onSelectDragEnd) and eventToCanvasPoint clamps back
    // into canvas bounds, so this reliably maxes out the pan.
    const cb = await canvasBox(page);
    await page.mouse.move(cb.x + 60, cb.y + 60);
    await page.mouse.down();
    await page.mouse.move(cb.x - 100, cb.y - 100, { steps: 5 });
    await page.mouse.up();

    const after = await samplePixel(page, 60, 60);
    const rectAfter = await page.locator('#select-rect').boundingBox();

    // The frame itself doesn't move during a pan — only the content under it.
    expect(Math.abs(rectAfter!.x - rectBefore!.x)).toBeLessThan(1);
    expect(Math.abs(rectAfter!.y - rectBefore!.y)).toBeLessThan(1);

    // The pixel at that fixed screen location changed substantially —
    // proof the image content actually moved underneath it.
    const dist = Math.hypot(after[0] - before[0], after[1] - before[1], after[2] - before[2]);
    expect(dist).toBeGreaterThan(100);
  });

  test('zoom in/out buttons change the zoom readout, and Fit resets it', async ({ page }) => {
    await expect(page.locator('#select-zoom-readout')).toHaveText('100%');
    await page.locator('#select-zoom-in-btn').click();
    await expect(page.locator('#select-zoom-readout')).toHaveText('150%'); // ZOOM_BUTTON_STEP = 1.5

    await page.locator('#select-zoom-in-btn').click();
    await expect(page.locator('#select-zoom-readout')).toHaveText('225%');

    await page.locator('#select-zoom-out-btn').click();
    await expect(page.locator('#select-zoom-readout')).toHaveText('150%');

    await page.locator('#select-zoom-fit-btn').click();
    await expect(page.locator('#select-zoom-readout')).toHaveText('100%');
  });

  test('Clear removes the selection box and disables "Use selection"', async ({ page }) => {
    await dragOnCanvas(page, 20, 20, 100, 100);
    await expect(page.locator('#select-rect')).toBeVisible();
    await expect(page.locator('#select-confirm-btn')).toBeEnabled();

    await page.locator('#select-clear-btn').click();
    await expect(page.locator('#select-rect')).toBeHidden();
    await expect(page.locator('#select-confirm-btn')).toBeDisabled();
  });

  test('"Use selection" crops to the drawn rectangle and the crop flows into tracing', async ({ page }) => {
    // Turn auto-trim off so this test isolates the plain screen->source
    // rect mapping (selectionRectToSourceRect) without #6's bbox-tightening
    // on top of it — that combination is covered by the next test.
    await page.locator('#select-autotrim-btn').click();
    await expect(page.locator('#select-autotrim-btn')).toHaveAttribute('aria-pressed', 'false');

    await dragOnCanvas(page, 20, 20, 100, 100); // ~80x80 display px box
    await page.locator('#select-confirm-btn').click();

    await expect(page.locator('#thumb-wrap')).toBeVisible();
    await expect(page.locator('#select-wrap')).toBeHidden();
    await expect(page.locator('#trace-btn')).toBeEnabled();

    const naturalWidth = await page.locator('#thumb-img').evaluate((img: HTMLImageElement) => img.naturalWidth);
    const naturalHeight = await page.locator('#thumb-img').evaluate((img: HTMLImageElement) => img.naturalHeight);
    // 80 display px / selectBaseScale (~0.508 for this 512px-wide fixture)
    // ~= 157 source px. Generous tolerance for scale rounding, but tight
    // enough to prove the crop used the drawn rect, not the whole 512x512
    // sheet or some unrelated size.
    expect(naturalWidth).toBeGreaterThan(120);
    expect(naturalWidth).toBeLessThan(200);
    expect(naturalHeight).toBeGreaterThan(120);
    expect(naturalHeight).toBeLessThan(200);

    // Prove the crop actually flows downstream into the trace pipeline,
    // not just that the thumbnail updated.
    await page.locator('#trace-btn').click();
    await expect(page.locator('#status')).toHaveText('Done — SVG ready ✓', { timeout: 15000 });
    await expect(page.locator('#svg-result')).toBeVisible();
  });

  test('auto-trim (default on) tightens a loose selection to the subject, producing a smaller crop than the drawn rectangle implies', async ({ page }) => {
    // Uses AA_SHEET_FIXTURE (anti-aliased icon edges), not SHEET_FIXTURE —
    // see the "known bugs" describe block below for exactly why the plain
    // sharp-edged fixture can't demonstrate correct auto-trim behavior.
    await uploadSheet(page, AA_SHEET_FIXTURE);
    await expect(page.locator('#select-autotrim-btn')).toHaveAttribute('aria-pressed', 'true');

    // A deliberately loose rectangle — well beyond the square icon's own
    // display bounds (~20,20-102,102) on every side, mapping to a raw
    // source rect of roughly 290x290 (5,5-150,150 display / ~0.5 scale).
    // (Starting at 5,5 rather than 0,0: .select-canvas-wrap's border-radius
    // clips the canvas's literal corner pixel, so document.elementFromPoint
    // there resolves to the wrapper, not the canvas -- confirmed while
    // developing this test. Nothing to do with the app's selection logic,
    // just a hit-testing edge a real drag would never start exactly on.)
    // #6 auto-trim should tighten this down to the icon's actual bounding
    // box (160x160 source px) plus AUTO_TRIM_MARGIN_PX=2 padding on each
    // side (~164x164), not use the loose rect verbatim.
    await dragOnCanvas(page, 5, 5, 150, 150);
    await page.locator('#select-confirm-btn').click();
    await expect(page.locator('#thumb-wrap')).toBeVisible();

    const naturalWidth = await page.locator('#thumb-img').evaluate((img: HTMLImageElement) => img.naturalWidth);
    const naturalHeight = await page.locator('#thumb-img').evaluate((img: HTMLImageElement) => img.naturalHeight);

    // Far tighter than the ~290px the loose drawn rect implies, and close
    // to the icon's true ~164px bounding box — generous tolerance for the
    // Otsu-threshold detection's exact edge, but tight enough to prove
    // auto-trim actually ran rather than falling back to the raw rect.
    expect(naturalWidth).toBeLessThan(220);
    expect(naturalHeight).toBeLessThan(220);
    expect(naturalWidth).toBeGreaterThan(130);
    expect(naturalHeight).toBeGreaterThan(130);
  });
});

test.describe('selection UI — auto-trim on sharp-edged selections (regression for #19)', () => {
  // #19 fixed a bug where computeOtsuThreshold (js/app.js ~1354) returned
  // exactly 0 on perfectly bimodal histograms (e.g. a flat-fill,
  // non-anti-aliased image), which made auto-trim's mask go empty and
  // silently no-op instead of tightening the crop. Fixed by clamping
  // computeOtsuThreshold's result to [1,254] at the source. This test
  // pins that fix: a sharp-edged selection with auto-trim on must come
  // out meaningfully tighter than the same selection with auto-trim off.

  test('auto-trim tightens a perfectly sharp-edged selection instead of leaving it untrimmed', async ({ page }) => {
    // Same loose rectangle as the passing auto-trim test above, but on
    // SHEET_FIXTURE (sharp/binary edges) instead of AA_SHEET_FIXTURE.
    // First pass: auto-trim OFF, to establish what an untrimmed crop of
    // this exact rectangle measures (the baseline).
    await uploadSheet(page, SHEET_FIXTURE);
    await page.locator('#select-autotrim-btn').click();
    await expect(page.locator('#select-autotrim-btn')).toHaveAttribute('aria-pressed', 'false');
    await dragOnCanvas(page, 5, 5, 150, 150);
    await page.locator('#select-confirm-btn').click();
    await expect(page.locator('#thumb-wrap')).toBeVisible();
    const rawWidth = await page.locator('#thumb-img').evaluate((img: HTMLImageElement) => img.naturalWidth);

    // Second pass: same rectangle, fresh upload, auto-trim left ON
    // (default). Should come out dramatically smaller than rawWidth
    // (tight around the ~160px-wide square icon, like the AA-fixture
    // test above measures), proving auto-trim actually ran.
    await uploadSheet(page, SHEET_FIXTURE);
    await expect(page.locator('#select-autotrim-btn')).toHaveAttribute('aria-pressed', 'true');
    await dragOnCanvas(page, 5, 5, 150, 150);
    await page.locator('#select-confirm-btn').click();
    await expect(page.locator('#thumb-wrap')).toBeVisible();
    const trimmedWidth = await page.locator('#thumb-img').evaluate((img: HTMLImageElement) => img.naturalWidth);

    expect(trimmedWidth).toBeLessThan(rawWidth - 40);
  });
});

test.describe('selection UI — touch input (issue #18: mobile drag-select)', () => {
  test.use({ hasTouch: true });

  // Dispatches a raw touchstart -> touchmove(s) -> touchend sequence
  // directly at the element via script-level `element.dispatchEvent`,
  // rather than relying on browser touch-to-mouse compatibility-event
  // synthesis. This is deliberate: compat mouse events are only
  // synthesized by the browser's real input pipeline for genuine
  // hardware/OS-originated touch input, never for script-dispatched
  // TouchEvents — so this method tests exactly and only whether the app
  // itself listens for touch input, with no risk of the mousedown/
  // mousemove/mouseup handlers accidentally firing via some synthesis path
  // and masking the gap. (Separately: even on a real device, compat mouse
  // events -- where a browser chooses to synthesize them at all -- are
  // limited to a single click-like mousedown+mouseup pair fired after
  // touchend, not a continuous mousemove during the touch-move phase, so
  // they would not produce a live drag rectangle here either way; a
  // 0-sized box from a single synthesized point would fail the MIN_SELECT_PX
  // check the same way the "drag smaller than minimum" desktop test above
  // does.)
  async function dispatchTouchDrag(page: Page, x1: number, y1: number, x2: number, y2: number) {
    await page.evaluate(({ x1, y1, x2, y2 }) => {
      const el = document.getElementById('select-canvas')!;
      const rect = el.getBoundingClientRect();
      let idSeq = 1;
      function fire(type: string, x: number, y: number) {
        const touch = new Touch({
          identifier: idSeq,
          target: el,
          clientX: rect.left + x,
          clientY: rect.top + y,
        });
        el.dispatchEvent(new TouchEvent(type, {
          bubbles: true,
          cancelable: true,
          touches: type === 'touchend' ? [] : [touch],
          targetTouches: type === 'touchend' ? [] : [touch],
          changedTouches: [touch],
        }));
      }
      fire('touchstart', x1, y1);
      fire('touchmove', (x1 + x2) / 2, (y1 + y2) / 2);
      fire('touchmove', x2, y2);
      fire('touchend', x2, y2);
    }, { x1, y1, x2, y2 });
  }

  // Regression coverage for #20 (mobile touch support): js/app.js now
  // routes touchstart/touchmove/touchend on #select-canvas through the
  // same onSelectDragStart/onSelectDrag/onSelectDragEnd state machine as
  // mouse input, via a shared eventToCanvasPoint helper that resolves
  // coordinates from e.touches[0]/e.changedTouches[0]/e itself. This
  // pins that a real touch drag draws a selection box and enables
  // confirmation, same as the equivalent mouse drag does above.
  test('touch drag-select on #select-canvas draws a selection box', async ({ page }) => {
    await uploadSheet(page);
    await expect(page.locator('#select-rect')).toBeHidden();
    await expect(page.locator('#select-confirm-btn')).toBeDisabled();

    // Same geometry as the passing "dragging draws a new selection box"
    // mouse test above, replayed via touch.
    await dispatchTouchDrag(page, 20, 20, 100, 100);

    await expect(page.locator('#select-rect')).toBeVisible();
    await expect(page.locator('#select-confirm-btn')).toBeEnabled();
  });
});
